### ISSUE TITLE
Cannot POST /...

### ISSUE THREAD

**Issue by rvan1** [justinwoo/ember-cli-api-stub-static#3]
This is a helpful alternative to api-stub, for CLI, but I have an action which POSTs some search criteria (JSON) at a URL and for this I get "404 Not Found" and "Cannot POST". I have response JSON setup up in "../server/routes", and can "GET" the JSON, but why won't it also work with a POST method?

**Comment by justinwoo** [comment]
the code for this module is quite naive: https://github.com/justinwoo/ember-cli-api-stub-static/blob/master/blueprints/api-stub-static/files/server/index.js

it just uses the request url to walk the paths and respond to GET requests with a index.json file's contents.

**Comment by rvan1** [comment]
Can it be revised to also respond to POST requests or is it not possible?

**Comment by justinwoo** [comment]
Sorry, I don't use this anymore.
